name: "ENVIRO+HA"
description: "Home Assistant add on for the enviro+ board attached on the pi running HA"
version: "1.2.1"
slug: "enviroha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1
